language: python

python:
  - "3.6"

addons:
  postgresql: "9.5"
    
install:
  - pip install -r requirements.txt

before_script:
#   - python manage.py makemigrations
#   - python manage.py migrate

script:
  - psql -c 'create database hms;' -U postgres
  - coveralls
  
after_script:
  - coveralls
